# Google Sheets + Service Account Configuration
SERVICE_ACCOUNT_FILE = "theta-reserve-472516-h1-b2f908ac6210.json"
SPREADSHEET_ID = "1CW62XUrBmI7O6LZ-2EUyw6oVKfx871oE2ZD_KF02fxg"

# Optional sheet tab names
INPUT_SHEET_NAME = "Input"
OUTPUT_SHEET_NAME = "Output"
